CREATE TABLE `mi_cloud_public_products` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '产品id',
  `union_id` varchar(45) NOT NULL DEFAULT ''COMMENT '隐藏直实Id',
  `avatar` varchar(255) NOT NULL DEFAULT '' COMMENT '封面',
  `cover` varchar(255) NOT NULL DEFAULT '' COMMENT '背面',
  `sn` varchar(45) NOT NULL DEFAULT '' COMMENT '产品编号',
  `name` varchar(64) NOT NULL DEFAULT '' COMMENT '产品名称',
  `pinyin` varchar(45) NOT NULL DEFAULT '' COMMENT '首拼字母(SPZM)',
  `brand_name` varchar(45) NOT NULL DEFAULT '' COMMENT '商品品牌',
  `feature` varchar(45) NOT NULL DEFAULT '' COMMENT '产品卖点',
  `price` bigint(20) NOT NULL DEFAULT '0' COMMENT '零售价格、不低于a_price',
  `spec` int(11) NOT NULL DEFAULT '0' COMMENT '规格',
  `spec_name` varchar(16) NOT NULL DEFAULT '瓶' COMMENT '最小规格名称，袋、瓶',
  `spec_weight` int(11) NOT NULL DEFAULT '0' COMMENT '最小规格重量（含包装）',
  `pk_amount` int(11) NOT NULL DEFAULT '1' COMMENT '装箱数量',
  `pk_weight` int(11) NOT NULL DEFAULT '1' COMMENT '装箱后总重量（包含包装）',
  `pack_name` varchar(16) NOT NULL DEFAULT '箱' COMMENT '打包后的名称',
  `keep_life` mediumint(9) NOT NULL DEFAULT '0' COMMENT '开启保质期(需要开起批次号)',
  `keep_life_unit` varchar(64) NOT NULL DEFAULT '天' COMMENT '1*24表天，7*24表周，30*24表月，365*24表年，默认天',
  `storage_conditions` varchar(64) NOT NULL DEFAULT '' COMMENT '保存方法',
  `transportation_conditions` varchar(64) NOT NULL DEFAULT '' COMMENT '运输条件',
  `unit` varchar(2) NOT NULL DEFAULT 'g' COMMENT '计量单位名默认g(克)还有ml(毫升)等',
  `habitat` varchar(45) NOT NULL DEFAULT '' COMMENT '产地（主要用于源材料）',
  `style` tinyint(4) NOT NULL DEFAULT '0' COMMENT '包装方式1预包装，2散装',
  `style_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1 称重2 量体3 点数\r\n',
  `units` varchar(512) NOT NULL DEFAULT '' COMMENT '扩展规格',
  `status` int(11) NOT NULL DEFAULT '0' COMMENT '1有效',
  `intime` int(11) NOT NULL DEFAULT '0' COMMENT '入库时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `product_code` (`union_id`) USING BTREE,
  KEY `prd_sn` (`sn`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC COMMENT = '产品公共库';
CREATE TABLE `mi_cloud_public_companies` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '行号Id',
  `union_id` varchar(45) NOT NULL COMMENT '隐藏直实Id',
  `province` varchar(45) NOT NULL DEFAULT '' COMMENT '省份',
  `name` varchar(45) NOT NULL DEFAULT '' COMMENT '公司',
  `avatar` varchar(255) NOT NULL DEFAULT '' COMMENT '头像图片路径',
  `pinyin` varchar(45) NOT NULL DEFAULT '' COMMENT '拼音',
  `pinyin_idx` varchar(1) NOT NULL DEFAULT '' COMMENT '首字母',
  `sn_code` varchar(45) NOT NULL DEFAULT '' COMMENT '公司代码',
  `legal_person` varchar(20) NOT NULL DEFAULT '' COMMENT '法人',
  `contact_name` varchar(20) NOT NULL DEFAULT '' COMMENT '联系人',
  `contact_phone` varchar(20) NOT NULL DEFAULT '' COMMENT '联系方式',
  `contact_mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '第二联系方式',
  `contact_email` varchar(200) NOT NULL DEFAULT '' COMMENT '联系人邮箱',
  `register_date` varchar(45) NOT NULL DEFAULT '注册时间',
  `expire_date` varchar(45) NOT NULL DEFAULT '失效时间',
  `area_code` varchar(64) NOT NULL DEFAULT '' COMMENT '2位或者12位跟统计用区域',
  `area_path` varchar(1024) NOT NULL DEFAULT '' COMMENT '带/的地址',
  `area_street` varchar(64) NOT NULL DEFAULT '' COMMENT '用户自己填写的',
  `address` varchar(100) NOT NULL DEFAULT '' COMMENT '全地址',
  `site` varchar(200) NOT NULL DEFAULT '' COMMENT '网站',
  `scale` varchar(30) NOT NULL DEFAULT '不详' COMMENT '规模',
  `longitude` varchar(15) NOT NULL DEFAULT '' COMMENT '经度',
  `latitude` varchar(15) NOT NULL DEFAULT '' COMMENT '纬度',
  `geo_hash` char(30) NOT NULL DEFAULT '' COMMENT 'geo_hash',
  `mark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `status` int(11) NOT NULL DEFAULT '0' COMMENT '1有效',
  `intime` int(11) NOT NULL DEFAULT '0' COMMENT '入库时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_code` (`union_id`) USING BTREE,
  KEY `idx_sn` (`sn_code`) USING BTREE,
  KEY `idx_py` (`pinyin`) USING BTREE,
  KEY `idx_prov` (`province`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC COMMENT = '公司信息公共库';